### ISSUE TITLE
Include sys/types.h in c_src/erl_blf.h

### ISSUE THREAD

**Issue by anthonyrisinger** [smarkets/erlang-bcrypt#16]
https://github.com/chef/erlang-bcrypt/pull/9/commits/a8f2ff42bea81bd2d7d24ab4e25f2f1c74b64dfb

```erlang
#include <sys/types.h>
```
This line is needed to compile on Alpine Linux (musl). Could we get at least this change in master?

Any idea why `u_*` types are in play here (vs. say `uint8_t`)? They look non-standard to me.

**Comment by rbruggem** [comment]
@anthonyrisinger 
This has been done (a63df34d). Thanks for raising this.
